version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 474495984432.dkr.ecr.ap-northeast-1.amazonaws.com
    - IMAGE_NAME=air_quality_ecr
    - IMAGE_URI=474495984432.dkr.ecr.ap-northeast-1.amazonaws.com/air_quality_ecr:latest
    - CONTAINER_NAME=airqualitymonitorcont
  build:
    commands:
    - echo Build started on `date`
    - echo $IMAGE_NAME
    - mvn clean package -Ddockerfile.skip
    - docker build -t $IMAGE_NAME .
  post_build:
    commands:
    - echo Build completed on `date`
    - echo $(docker images)
    - docker tag $IMAGE_NAME $IMAGE_URI
    - echo Pushing docker image
    - docker push $IMAGE_URI
    - echo push completed
    - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json
